---
title: "test"
author: "Keita Makino"
date: "7/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)

source("./importData.r")
source("./selectColumns.r")
```

```{r fig.width=12, fig.height=8}
raw = importData("covidV2")
employment = raw %>% selectColumns(c("ResponseId",paste("C04_", 1:9, sep = ""))) %>% mutate(sum = rowSums(.[,-1]) > 0) %>% select(ResponseId, sum)
before = raw %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3"))
after = raw %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3")) 
joined = inner_join(before,after) %>% inner_join(employment, "ResponseId") %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:4] = joined[,c(c(1,7)+i,13)]
}
colnames(data)[2:4] = c("before", "after", "isWorking")
data = data %>% mutate(before = as.numeric(before), after = as.numeric(after)) %>% filter(before <= 100 & before >= 0 & after <= 100 & after >= 0) %>% filter(!(key <= 3 & isWorking == F)) %>% mutate(sum = before + after) %>% filter (sum <= 20)
ggplot(data) + geom_histogram(aes(x = before), binwidth = 1) + facet_wrap(~key)
```

```{r fig.width=12, fig.height=8}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:3] = joined[,c(1,7)+i]
}
colnames(data)[2:3] = c("before", "after")
data = data %>% mutate(before = as.numeric(before), after = as.numeric(after*6)) %>% 
  filter(before <= 100 & before >= 0 & after <= 100 & after >= 0) %>%
  mutate(before = before + 5, after = after + 5) %>%
  mutate(before = before - before %% 6, after = after - after %% 6) %>%
  mutate(isBeforeLargerOrEqual = before >= after, isAfterLargerOrEqual = before <= after) %>%
  mutate(newBefore = ifelse(before > 0,1,0), newAfter = ifelse(after > 0,1,0)) %>%
  mutate(newBefore = newBefore + ifelse(before * isBeforeLargerOrEqual > 0,1,0), newAfter = newAfter + ifelse(after * isAfterLargerOrEqual > 0,1,0)) %>%
  group_by(key, newBefore, newAfter) %>% tally()
ggplot(data, aes(newBefore,newAfter,)) + geom_tile(aes( fill = n), alpha = 0.4) +
  geom_text(aes(label = n)) +
  scale_fill_viridis_c() +
  facet_wrap(~key)
```

```{r fig.width=12, fig.height=16}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3", "City")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3", "City")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:4] = joined[,c(1+i,8+i,7)]
}
colnames(data)[2:4] = c("before", "after", "city")
data = data %>% mutate(before = as.numeric(before), after = as.numeric(after*6)) %>% 
  filter(before <= 100 & before >= 0 & after <= 100 & after >= 0) %>%
  mutate(before = before + 5, after = after + 5) %>%
  mutate(before = before - before %% 6, after = after - after %% 6) %>%
  mutate(isBeforeLargerOrEqual = before >= after, isAfterLargerOrEqual = before <= after) %>%
  mutate(newBefore = ifelse(before > 0,1,0), newAfter = ifelse(after > 0,1,0)) %>%
  mutate(newBefore = newBefore + ifelse(before * isBeforeLargerOrEqual > 0,1,0), newAfter = newAfter + ifelse(after * isAfterLargerOrEqual > 0,1,0)) %>%
  group_by(key, newBefore, newAfter, city) %>%
  tally() %>%
  group_by(key,city) %>%
  mutate(freq = n / sum(n))
ggplot(data, aes(newBefore,newAfter)) + geom_tile(aes(fill = freq), alpha = 0.4) +
  geom_text(aes(label = freq %>% round(2))) +
  scale_fill_viridis_c() +
  facet_grid(city~key)
```

```{r fig.width=12, fig.height=8}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:3] = joined[,c(1,7)+i]
}
colnames(data)[2:3] = c("before", "after")
data = data %>%
  mutate(before = as.numeric(before), after = as.numeric(after)) %>%
  filter(before <= 100 & after <= 17 & before >= 0 & after >= 0 & (before > 0 | after > 0)) %>%
  mutate(diff = after*6 - before)
ggplot(data) + geom_vline(xintercept = 0, alpha = 0.3) + geom_histogram(aes(diff, fill = key), alpha = 0.7, binwidth = 5) + facet_wrap(~key)
```

```{r fig.width=16, fig.height=9}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3", "H07_1")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3", "H07_1")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:4] = joined[,c(1+i,8+i,7)]
}
colnames(data)[2:4] = c("before", "after", "H07_1")
data = data %>%
  mutate(before = as.numeric(before), after = as.numeric(after)) %>%
  filter(before <= 100 & after <= 17 & before >= 0 & after >= 0 & (before > 0 | after > 0)) %>%
  mutate(diff = after*6 - before)
ggplot(data, aes(x = diff)) + geom_vline(xintercept = 0, alpha = 0.3) +
  geom_histogram(aes(y = 5*..density.., fill = key), alpha = 0.7, binwidth = 5) +
  facet_grid(H07_1~key)
```

```{r fig.width=16, fig.height=9}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3", "I01_1")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3", "I01_1")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:4] = joined[,c(1+i,8+i,7)]
}
colnames(data)[2:4] = c("before", "after", "I01_1")
data = data %>%
  mutate(I01_1 = cut(I01_1, c(1920, 1935, 1950, 1965, 1980, 1995, 2010), labels = c("(1920-1935]", "(1935-1950]","(1950-1965]","(1965-1980]","(1980-1995]","(1995-2010]"))) %>%
  mutate(before = as.numeric(before), after = as.numeric(after)) %>%
  filter(before <= 100 & after <= 17 & before >= 0 & after >= 0 & (before > 0 | after > 0)) %>%
  mutate(diff = after*6 - before)
ggplot(data, aes(x = diff)) + geom_vline(xintercept = 0, alpha = 0.3) +
  geom_histogram(aes(y = 5*..density.., fill = key), alpha = 0.7, binwidth = 5) +
  facet_grid(I01_1~key)
```


```{r fig.width=16, fig.height=24}
before = importData("covidV2") %>% selectColumns(c("ResponseId","C11.1_1_1","C11.1_1_2","C11.1_1_3","C11.1_2_1","C11.1_2_2","C11.1_2_3", "City")) %>% na.exclude()
after = importData("covidV2") %>% selectColumns(c("ResponseId","C11.2_1_1","C11.2_1_2","C11.2_1_3","C11.2_2_1","C11.2_2_2","C11.2_2_3", "City")) %>% na.exclude()
joined = inner_join(before,after,c("ResponseId" = "ResponseId")) %>% select(-ResponseId)
data = data.frame(key = rep(1:6,each = dim(joined)[1]) %>% as.character)
for (i in 0:5) {
  data[(i*dim(joined)[1]+1):((i+1)*dim(joined)[1]),2:4] = joined[,c(1+i,8+i,7)]
}
colnames(data)[2:4] = c("before", "after", "City")
data = data %>%
  mutate(before = as.numeric(before), after = as.numeric(after)) %>%
  filter(before <= 100 & after <= 17 & before >= 0 & after >= 0 & (before > 0 | after > 0)) %>%
  mutate(diff = after*6 - before)
ggplot(data, aes(x = diff)) + geom_vline(xintercept = 0, alpha = 0.3) +
  geom_histogram(aes(y = 5*..density.., fill = key), alpha = 0.7, binwidth = 5) +
  facet_grid(City~key)
```