---
title: "test"
author: "Keita Makino"
date: "7/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(psych)
library(MASS)
library(apollo)
library(tidyverse)
library(fastDummies)

source("./importData.r")
source("./selectColumns.r")
```

```{r}
nameBase = c(
  "biz_car",
  "biz_air",
  "biz_oth",
  "rec_car",
  "rec_air",
  "rec_oth"
)

raw = importData("covidV2") %>%
  filter(City != "Vancouver" & City != "Toronto")
```

```{r fig.width=12, fig.height=8}
before = raw %>% selectColumns(
  c(
    "ResponseId",
    "C11.1_1_1",
    "C11.1_1_2",
    "C11.1_1_3",
    "C11.1_2_1",
    "C11.1_2_2",
    "C11.1_2_3"
  )
) %>% na.exclude()
during = raw %>% selectColumns(
  c(
    "ResponseId",
    "C11.2_1_1",
    "C11.2_1_2",
    "C11.2_1_3",
    "C11.2_2_1",
    "C11.2_2_2",
    "C11.2_2_3"
  )
) %>% na.exclude()

joinedRaw = inner_join(before, during, c("ResponseId" = "ResponseId"))
colnames(joinedRaw) = c(
  "ResponseId",
  paste(nameBase, "_before", sep = ""),
  paste(nameBase, "_during", sep = "")
)

joinedRaw %>%
  gather(key,value, -"ResponseId") %>%
  filter(value >=0 & value < 100) %>%
  ggplot() + geom_histogram(aes(x = value), binwidth = 1) +
  facet_wrap(~key)

joined = joinedRaw[,"ResponseId"]

for (name in nameBase) {
  num = joinedRaw[, c(paste(name, "_before", sep = ""), paste(name, "_during", sep = ""))]
  num[num[,1] < 0 | num[,1] > 100, 1] = NaN
  num[num[,2] < 0 | num[,2] > 17, 2] = NaN
  num[, name] = ifelse(num[,2] > round(num[,1] / 6), "greater", ifelse(num[,2] < round(num[,1] / 6), "smaller", "same")) %>%
    factor(levels = c("smaller","same", "greater"))
  # num[,paste(name, "_isUser", sep = "")] = rowSums(num[,1:2]) > 0
  joined = cbind(joined,num[,3])
}
joined = joined %>% as.data.frame()
colnames(joined) = c("ResponseId", nameBase)
```

no change
higher in 2019
higehr in 2020

```{r fig.width=16, fig.height=24}
socio = raw %>% selectColumns(c("ResponseId","City", "D01", "D09_2", "D09_7", "H03_1", "I01_1", "I04_4", "I05", "I09_USD", "I07")) %>% 
  mutate(H03_1 = ifelse(H03_1 == "", 0, H03_1) %>% as.numeric()) %>%
  mutate(Age = cut(I01_1, c(1920, 1965, 1980, 1995, 2010), labels = c("(1920-1965]","(1965-1980]","(1980-1995]","(1995-2010]"))) %>%
  mutate(Gen = case_when(I05 > 1 ~ "Non-Female", T ~ "Female")) %>%
  mutate(Edc = case_when(I07 > 3 ~ ">Bachelor", T ~ "<=Bachelor")) %>%
  mutate(Chl = case_when(D09_2 > 0 ~ "Yes", T ~ "No")) %>%
  mutate(Inc = case_when(I09_USD < 3 ~ "<25,000", I09_USD > 4 ~ ">=100,000", T ~ "50,000-99,999")) %>%
  mutate(Rac = case_when(I04_4 == 1 ~ "White", T ~ "Other")) %>%
  mutate(Vpp = case_when(D09_7 > H03_1 ~ "Sufficient", T ~ "Deficient")) %>%
  mutate(Ngh = case_when(D01 == 1 ~ "Urban", T ~ "Non-Urban")) %>%
  mutate(City = case_when(City %in% c("LA", "SF", "Sacramento", "Seattle", "SD", "Denver", "SLC") ~ "West",
                          City %in% c("Kansas", "Detroit", "Chicago") ~ "Midwest",
                          City %in% c("Atlanta", "Tampa", "DC") ~ "South",
                          City %in% c("NYC", "Boston") ~ "Northeast")) %>%
  mutate_at(c("City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac"), as.factor) %>%
  mutate(Age = factor(Age, levels = rev(c("(1920-1965]","(1965-1980]","(1980-1995]","(1995-2010]")))) %>%
  mutate(Inc = factor(Inc, levels = c("<25,000","50,000-99,999",">=100,000"))) %>%
  mutate(Rac = factor(Rac, levels = c("White","Other"))) %>%
  mutate(Ngh = factor(Ngh, levels = c("Urban","Non-Urban"))) %>%
  mutate(City = factor(City, levels = c("West", "Midwest", "South", "Northeast"))) %>%
  select(ResponseId, City, Age, Inc, Vpp, Edc, Gen, Ngh, Rac)
```

```{r fig.width=8, fig.height=4.8}
c("City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac") %>% map( ~ {
  data = socio %>%
    select(ResponseId, value = .x) %>%
    group_by(value) %>%
    summarize(n = n()) %>%
    mutate(labelPos = sum(n) - cumsum(n) + n / 2)
  ggplot(data) +
    geom_bar(aes(x = 1, y = n, fill = value), stat = "identity") +
    geom_text(aes(x = 1.15, y = labelPos, label = ifelse(n>=50, n, ""))) +
    coord_polar("y", direction = -1) +
    theme_bw() +
    ylab(.x) +
    theme(axis.title.y = element_blank())
})
```

```{r}
list = paste("A0", 1:5, sep = "") %>% 
                    map(function(x) paste(x,"_", 1:5, sep = "")) %>% 
                    unlist
list[5] = "A01_6"
attitudeA = raw %>%
  selectColumns(c("ResponseId", list)) %>%
  na.exclude() %>% .[,c(-10,-23)]
faA = factanal(attitudeA[,-1], factors = 6, rotation = "promax", score = "Bartlett")
attitudeA = data.frame(attitudeA$ResponseId, faA$scores)
colnames(attitudeA) = c("ResponseId" ,"FA1A", "FA2A", "FA3A", "FA4A", "FA5A", "FA6A")
write.csv(faA$loadings[,1:6], "factorA.csv")
```

```{r fig.width=16, fig.height=24}
attitudeH = raw %>%
  selectColumns(c("ResponseId", paste("H07_", 1:17, sep = ""))) %>%
  na.exclude()
faH = factanal(attitudeH[,-1], factors = 4, rotation = "promax", score = "Bartlett")
attitudeH = data.frame(attitudeH$ResponseId, faH$scores)
colnames(attitudeH) = c("ResponseId", "FA1H", "FA2H", "FA3H", "FA4H")
write.csv(faH$loadings[,1:4], "factorH.csv")
```

```{r fig.width=16, fig.height=24}
fut = raw %>% selectColumns(c("ResponseId", "C13_3")) %>%
  mutate(future = case_when(C13_3 < 3 ~ "less", C13_3 > 3 ~ "more", T ~ "same"))  %>%
  select(-C13_3) %>%
  mutate(future = factor(future, levels = c("less","same","more")) %>% as.numeric())
```

```{r}
database = inner_join(joined,socio) %>%
  inner_join(attitudeA) %>%
  inner_join(attitudeH) %>%
  inner_join(future)
colnames(database)[1] = "ID"
database$ID = 1:dim(database)[1]
database = database %>% filter(!is.na(biz_car)) %>% mutate_at(
  c("City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac"), as.numeric
)
```

```{r}
apollo_control <- list(
  modelName = "mnl",
  modelDescr = "MNL with Factor Analysis",
  indivID = "ID"
)

choiceAnalysis_settings <- list(
  alternatives = c(smlr = 1, same = 2, grtr = 3),
  avail = 1,
  choiceVar = database$biz_car,
  explanators = database[, c(
    "City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac",
    "FA1A",
    "FA2A",
    "FA3A",
    "FA4A",
    "FA5A",
    "FA6A",
    "FA1H",
    "FA2H",
    "FA3H",
    "FA4H"
  )]
)

apollo_choiceAnalysis(choiceAnalysis_settings, apollo_control, database)

apollo_beta <- c(
  asc_smlr = 0,
  asc_grtr = 0,
  b_FA1A_smlr = 0,
  b_FA2A_smlr = 0,
  b_FA3A_smlr = 0,
  b_FA4A_smlr = 0,
  b_FA5A_smlr = 0,
  b_FA6A_smlr = 0,
  b_FA1H_smlr = 0,
  b_FA2H_smlr = 0,
  b_FA3H_smlr = 0,
  b_FA4H_smlr = 0,
  b_City_Midwest_smlr = 0,
  b_City_South_smlr = 0,
  b_City_Northeast_smlr = 0,
  b_Age_Millenials_smlr = 0,
  b_Age_GenX_smlr = 0,
  b_Age_Older_smlr = 0,
  b_Inc_Mid_smlr = 0,
  b_Inc_High_smlr = 0,
  b_Vpp_Sufficient_smlr = 0,
  b_Edc_MoreBachelor_smlr = 0,
  b_Gen_NonFemale_smlr = 0,
  b_Ngh_NonUrban_smlr = 0,
  b_Rac_Other_smlr = 0,
  b_FA1A_grtr = 0,
  b_FA2A_grtr = 0,
  b_FA3A_grtr = 0,
  b_FA4A_grtr = 0,
  b_FA5A_grtr = 0,
  b_FA6A_grtr = 0,
  b_FA1H_grtr = 0,
  b_FA2H_grtr = 0,
  b_FA3H_grtr = 0,
  b_FA4H_grtr = 0,
  b_City_Midwest_grtr = 0,
  b_City_South_grtr = 0,
  b_City_Northeast_grtr = 0,
  b_Age_Millenials_grtr = 0,
  b_Age_GenX_grtr = 0,
  b_Age_Older_grtr = 0,
  b_Inc_Mid_grtr = 0,
  b_Inc_High_grtr = 0,
  b_Vpp_Sufficient_grtr = 0,
  b_Edc_MoreBachelor_grtr = 0,
  b_Gen_NonFemale_grtr = 0,
  b_Ngh_NonUrban_grtr = 0,
  b_Rac_Other_grtr = 0
)

apollo_fixed <- c()

apollo_inputs <- apollo_validateInputs()

apollo_probabilities <- function(apollo_beta, apollo_inputs, functionality = "estimate") {
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))
  
  P <- list()
  
  V <- list()
  V[["same"]] <- 0
  V[["smlr"]] <- asc_smlr +
    b_FA1A_smlr * FA1A +
    b_FA2A_smlr * FA2A +
    b_FA3A_smlr * FA3A +
    b_FA4A_smlr * FA4A +
    b_FA5A_smlr * FA5A +
    b_FA6A_smlr * FA6A +
    b_FA1H_smlr * FA1H +
    b_FA2H_smlr * FA2H +
    b_FA3H_smlr * FA3H +
    b_FA4H_smlr * FA4H +
    b_City_Midwest_smlr * (City == 2) +
    b_City_South_smlr * (City == 3) +
    b_City_Northeast_smlr * (City == 4)  +
    b_Age_Millenials_smlr * (Age == 2) +
    b_Age_GenX_smlr * (Age == 3) +
    b_Age_Older_smlr * (Age == 4)  +
    b_Inc_Mid_smlr * (Inc == 2)  +
    b_Inc_High_smlr * (Inc == 3) +
    b_Vpp_Sufficient_smlr * (Vpp == 2) +
    b_Edc_MoreBachelor_smlr * (Edc == 2) +
    b_Gen_NonFemale_smlr * (Gen == 2)  +
    b_Ngh_NonUrban_smlr * (Ngh == 2) +
    b_Rac_Other_smlr * (Rac == 2)
  V[["grtr"]] <- asc_grtr +
    b_FA1A_grtr * FA1A +
    b_FA2A_grtr * FA2A +
    b_FA3A_grtr * FA3A +
    b_FA4A_grtr * FA4A +
    b_FA5A_grtr * FA5A +
    b_FA6A_grtr * FA6A +
    b_FA1H_grtr * FA1H +
    b_FA2H_grtr * FA2H +
    b_FA3H_grtr * FA3H +
    b_FA4H_grtr * FA4H +
    b_City_Midwest_grtr * (City == 2) +
    b_City_South_grtr * (City == 3) +
    b_City_Northeast_grtr *(City == 4)  +
    b_Age_Millenials_grtr * (Age == 2) +
    b_Age_GenX_grtr * (Age == 3) +
    b_Age_Older_grtr * (Age == 4)  +
    b_Inc_Mid_grtr * (Inc == 2)  +
    b_Inc_High_grtr * (Inc == 3) +
    b_Vpp_Sufficient_grtr * (Vpp == 2) +
    b_Edc_MoreBachelor_grtr * (Edc == 2) +
    b_Gen_NonFemale_grtr * (Gen == 2)  +
    b_Ngh_NonUrban_grtr * (Ngh == 2) +
    b_Rac_Other_grtr * (Rac == 2)
  
  mnl_settings <- list(
    alternatives = c(smlr = 1, same = 2, grtr = 3),
    avail = 1,
    choiceVar = biz_car,
    V = V
  )
  
  P[["model"]] <- apollo_mnl(mnl_settings, functionality)
  
  P <- apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

model <- apollo_estimate(apollo_beta, apollo_fixed, apollo_probabilities, apollo_inputs)

apollo_modelOutput(model)
apollo_saveOutput(model)
sink(paste(model$apollo_control$modelName, "_additional_output.txt", sep = ""), split = TRUE)
if (sink.number() > 0) sink()
```

```{r}
apollo_control <- list(
  modelName = "mnl2",
  modelDescr = "MNL with Factor Analysis",
  indivID = "ID"
)

choiceAnalysis_settings <- list(
  alternatives = c(smlr = 1, same = 2, grtr = 3),
  avail = 1,
  choiceVar = database$future,
  explanators = database[, c(
    "City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac",
    "FA1A",
    "FA2A",
    "FA3A",
    "FA4A",
    "FA5A",
    "FA6A",
    "FA1H",
    "FA2H",
    "FA3H",
    "FA4H"
  )]
)

apollo_choiceAnalysis(choiceAnalysis_settings, apollo_control, database)


apollo_inputs <- apollo_validateInputs()

apollo_probabilities <- function(apollo_beta, apollo_inputs, functionality = "estimate") {
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))
  
  P <- list()
  
  V <- list()
  V[["same"]] <- 0
  V[["smlr"]] <- asc_smlr +
    b_FA1A_smlr * FA1A +
    b_FA2A_smlr * FA2A +
    b_FA3A_smlr * FA3A +
    b_FA4A_smlr * FA4A +
    b_FA5A_smlr * FA5A +
    b_FA6A_smlr * FA6A +
    b_FA1H_smlr * FA1H +
    b_FA2H_smlr * FA2H +
    b_FA3H_smlr * FA3H +
    b_FA4H_smlr * FA4H +
    b_City_Midwest_smlr * (City == 2) +
    b_City_South_smlr * (City == 3) +
    b_City_Northeast_smlr * (City == 4)  +
    b_Age_Millenials_smlr * (Age == 2) +
    b_Age_GenX_smlr * (Age == 3) +
    b_Age_Older_smlr * (Age == 4)  +
    b_Inc_Mid_smlr * (Inc == 2)  +
    b_Inc_High_smlr * (Inc == 3) +
    b_Vpp_Sufficient_smlr * (Vpp == 2) +
    b_Edc_MoreBachelor_smlr * (Edc == 2) +
    b_Gen_NonFemale_smlr * (Gen == 2)  +
    b_Ngh_NonUrban_smlr * (Ngh == 2) +
    b_Rac_Other_smlr * (Rac == 2)
  V[["grtr"]] <- asc_grtr +
    b_FA1A_grtr * FA1A +
    b_FA2A_grtr * FA2A +
    b_FA3A_grtr * FA3A +
    b_FA4A_grtr * FA4A +
    b_FA5A_grtr * FA5A +
    b_FA6A_grtr * FA6A +
    b_FA1H_grtr * FA1H +
    b_FA2H_grtr * FA2H +
    b_FA3H_grtr * FA3H +
    b_FA4H_grtr * FA4H +
    b_City_Midwest_grtr * (City == 2) +
    b_City_South_grtr * (City == 3) +
    b_City_Northeast_grtr *(City == 4)  +
    b_Age_Millenials_grtr * (Age == 2) +
    b_Age_GenX_grtr * (Age == 3) +
    b_Age_Older_grtr * (Age == 4)  +
    b_Inc_Mid_grtr * (Inc == 2)  +
    b_Inc_High_grtr * (Inc == 3) +
    b_Vpp_Sufficient_grtr * (Vpp == 2) +
    b_Edc_MoreBachelor_grtr * (Edc == 2) +
    b_Gen_NonFemale_grtr * (Gen == 2)  +
    b_Ngh_NonUrban_grtr * (Ngh == 2) +
    b_Rac_Other_grtr * (Rac == 2)
  
  mnl_settings <- list(
    alternatives = c(smlr = 1, same = 2, grtr = 3),
    avail = 1,
    choiceVar = future,
    V = V
  )
  
  P[["model"]] <- apollo_mnl(mnl_settings, functionality)
  
  P <- apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

model <- apollo_estimate(apollo_beta, apollo_fixed, apollo_probabilities, apollo_inputs)

apollo_modelOutput(model)
apollo_saveOutput(model)
sink(paste(model$apollo_control$modelName, "_additional_output.txt", sep = ""), split = TRUE)
if (sink.number() > 0) sink()
```

```{r}
apollo_control <- list(
  modelName = "mnl3",
  modelDescr = "MNL with Factor Analysis",
  indivID = "ID"
)

choiceAnalysis_settings <- list(
  alternatives = c(smlr = 1, same = 2, grtr = 3),
  avail = 1,
  choiceVar = database$biz_car,
  explanators = database[, c(
    "City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac"
  )]
)

apollo_choiceAnalysis(choiceAnalysis_settings, apollo_control, database)

apollo_beta <- c(
  asc_smlr = 0,
  asc_grtr = 0,
  b_City_Midwest_smlr = 0,
  b_City_South_smlr = 0,
  b_City_Northeast_smlr = 0,
  b_Age_Millenials_smlr = 0,
  b_Age_GenX_smlr = 0,
  b_Age_Older_smlr = 0,
  b_Inc_Mid_smlr = 0,
  b_Inc_High_smlr = 0,
  b_Vpp_Sufficient_smlr = 0,
  b_Edc_MoreBachelor_smlr = 0,
  b_Gen_NonFemale_smlr = 0,
  b_Ngh_NonUrban_smlr = 0,
  b_Rac_Other_smlr = 0,
  b_City_Midwest_grtr = 0,
  b_City_South_grtr = 0,
  b_City_Northeast_grtr = 0,
  b_Age_Millenials_grtr = 0,
  b_Age_GenX_grtr = 0,
  b_Age_Older_grtr = 0,
  b_Inc_Mid_grtr = 0,
  b_Inc_High_grtr = 0,
  b_Vpp_Sufficient_grtr = 0,
  b_Edc_MoreBachelor_grtr = 0,
  b_Gen_NonFemale_grtr = 0,
  b_Ngh_NonUrban_grtr = 0,
  b_Rac_Other_grtr = 0
)

apollo_choiceAnalysis(choiceAnalysis_settings, apollo_control, database)

apollo_inputs <- apollo_validateInputs()

apollo_probabilities <- function(apollo_beta, apollo_inputs, functionality = "estimate") {
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))
  
  P <- list()
  
  V <- list()
  V[["same"]] <- 0
  V[["smlr"]] <- asc_smlr +
    b_City_Midwest_smlr * (City == 2) +
    b_City_South_smlr * (City == 3) +
    b_City_Northeast_smlr * (City == 4)  +
    b_Age_Millenials_smlr * (Age == 2) +
    b_Age_GenX_smlr * (Age == 3) +
    b_Age_Older_smlr * (Age == 4)  +
    b_Inc_Mid_smlr * (Inc == 2)  +
    b_Inc_High_smlr * (Inc == 3) +
    b_Vpp_Sufficient_smlr * (Vpp == 2) +
    b_Edc_MoreBachelor_smlr * (Edc == 2) +
    b_Gen_NonFemale_smlr * (Gen == 2)  +
    b_Ngh_NonUrban_smlr * (Ngh == 2) +
    b_Rac_Other_smlr * (Rac == 2)
  V[["grtr"]] <- asc_grtr +
    b_City_Midwest_grtr * (City == 2) +
    b_City_South_grtr * (City == 3) +
    b_City_Northeast_grtr *(City == 4)  +
    b_Age_Millenials_grtr * (Age == 2) +
    b_Age_GenX_grtr * (Age == 3) +
    b_Age_Older_grtr * (Age == 4)  +
    b_Inc_Mid_grtr * (Inc == 2)  +
    b_Inc_High_grtr * (Inc == 3) +
    b_Vpp_Sufficient_grtr * (Vpp == 2) +
    b_Edc_MoreBachelor_grtr * (Edc == 2) +
    b_Gen_NonFemale_grtr * (Gen == 2)  +
    b_Ngh_NonUrban_grtr * (Ngh == 2) +
    b_Rac_Other_grtr * (Rac == 2)
  
  mnl_settings <- list(
    alternatives = c(smlr = 1, same = 2, grtr = 3),
    avail = 1,
    choiceVar = biz_car,
    V = V
  )
  
  P[["model"]] <- apollo_mnl(mnl_settings, functionality)
  
  P <- apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

model <- apollo_estimate(apollo_beta, apollo_fixed, apollo_probabilities, apollo_inputs)

apollo_modelOutput(model)
apollo_saveOutput(model)
sink(paste(model$apollo_control$modelName, "_additional_output.txt", sep = ""), split = TRUE)
if (sink.number() > 0) sink()
```

```{r}
apollo_control <- list(
  modelName = "mnl4",
  modelDescr = "MNL with Factor Analysis",
  indivID = "ID"
)

choiceAnalysis_settings <- list(
  alternatives = c(smlr = 1, same = 2, grtr = 3),
  avail = 1,
  choiceVar = database$future,
  explanators = database[, c(
    "City", "Age", "Inc", "Vpp", "Edc", "Gen", "Ngh", "Rac"
  )]
)

apollo_choiceAnalysis(choiceAnalysis_settings, apollo_control, database)


apollo_inputs <- apollo_validateInputs()

apollo_probabilities <- function(apollo_beta, apollo_inputs, functionality = "estimate") {
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))
  
  P <- list()
  
  V <- list()
  V[["same"]] <- 0
  V[["smlr"]] <- asc_smlr +
    b_City_Midwest_smlr * (City == 2) +
    b_City_South_smlr * (City == 3) +
    b_City_Northeast_smlr * (City == 4)  +
    b_Age_Millenials_smlr * (Age == 2) +
    b_Age_GenX_smlr * (Age == 3) +
    b_Age_Older_smlr * (Age == 4)  +
    b_Inc_Mid_smlr * (Inc == 2)  +
    b_Inc_High_smlr * (Inc == 3) +
    b_Vpp_Sufficient_smlr * (Vpp == 2) +
    b_Edc_MoreBachelor_smlr * (Edc == 2) +
    b_Gen_NonFemale_smlr * (Gen == 2)  +
    b_Ngh_NonUrban_smlr * (Ngh == 2) +
    b_Rac_Other_smlr * (Rac == 2)
  V[["grtr"]] <- asc_grtr +
    b_City_Midwest_grtr * (City == 2) +
    b_City_South_grtr * (City == 3) +
    b_City_Northeast_grtr *(City == 4)  +
    b_Age_Millenials_grtr * (Age == 2) +
    b_Age_GenX_grtr * (Age == 3) +
    b_Age_Older_grtr * (Age == 4)  +
    b_Inc_Mid_grtr * (Inc == 2)  +
    b_Inc_High_grtr * (Inc == 3) +
    b_Vpp_Sufficient_grtr * (Vpp == 2) +
    b_Edc_MoreBachelor_grtr * (Edc == 2) +
    b_Gen_NonFemale_grtr * (Gen == 2)  +
    b_Ngh_NonUrban_grtr * (Ngh == 2) +
    b_Rac_Other_grtr * (Rac == 2)
  
  mnl_settings <- list(
    alternatives = c(smlr = 1, same = 2, grtr = 3),
    avail = 1,
    choiceVar = future,
    V = V
  )
  
  P[["model"]] <- apollo_mnl(mnl_settings, functionality)
  
  P <- apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

model <- apollo_estimate(apollo_beta, apollo_fixed, apollo_probabilities, apollo_inputs)

apollo_modelOutput(model)
apollo_saveOutput(model)
sink(paste(model$apollo_control$modelName, "_additional_output.txt", sep = ""), split = TRUE)
if (sink.number() > 0) sink()
```